### PR TITLE
Sending game duration over the wire!

### PR DESCRIPTION
**Pull request by RSNara**

### CODE REVIEW

**Comment by mandishshah** [comment]
Yeah your welcome kids

**Comment by RSNara** [comment]
Can this @mandishshah guy get back to work please?

**Comment by RSNara** [comment]
Like just this once. That's all I'm asking. Gosh...

**Comment by mandishshah** [comment]
Today is retrospective day lol. Catching up from what I missed yesterday. So is our api call "7 seconds slower" now ;)

**Comment by RSNara** [comment]
I can make it 7 seconds slower if you want. :P

**Pull request merged**
